// <auto-generated />
using System;
using CAP.Modules.Users.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CAP.Modules.Users.Data.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CAP.Modules.Users.Core.Domain.Utilizador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("InvitationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroSocio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores", "users");

                    b.HasDiscriminator<string>("UserType").HasValue("Base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CAP.Modules.Users.Core.Domain.Atleta", b =>
                {
                    b.HasBaseType("CAP.Modules.Users.Core.Domain.Utilizador");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EncarregadoEducacaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumeroCamisola")
                        .HasColumnType("integer");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("EncarregadoEducacaoId");

                    b.HasDiscriminator().HasValue("Atleta");
                });

            modelBuilder.Entity("CAP.Modules.Users.Core.Domain.EncarregadoEducacao", b =>
                {
                    b.HasBaseType("CAP.Modules.Users.Core.Domain.Utilizador");

                    b.HasDiscriminator().HasValue("EncarregadoEducacao");
                });

            modelBuilder.Entity("CAP.Modules.Users.Core.Domain.Treinador", b =>
                {
                    b.HasBaseType("CAP.Modules.Users.Core.Domain.Utilizador");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Treinador");
                });

            modelBuilder.Entity("CAP.Modules.Users.Core.Domain.Atleta", b =>
                {
                    b.HasOne("CAP.Modules.Users.Core.Domain.EncarregadoEducacao", "EncarregadoEducacao")
                        .WithMany("AtletasDependentes")
                        .HasForeignKey("EncarregadoEducacaoId");

                    b.Navigation("EncarregadoEducacao");
                });

            modelBuilder.Entity("CAP.Modules.Users.Core.Domain.EncarregadoEducacao", b =>
                {
                    b.Navigation("AtletasDependentes");
                });
#pragma warning restore 612, 618
        }
    }
}
