@startuml atividade_convocatoria
!include _cap_skin.puml
title Diagrama de atividade — **Publicação de convocatória**

|Treinador|
start
:Solicita publicação de\nconvocatória em curso;

|Sistema|
if (Estado = Rascunho\nE nº atletas > 0 ?) then (sim)
  :Persistir **Publicada**\ncom carimbo temporal;
  fork
    :Para cada atleta convocado:\nenviar notificação;
  fork again
    :Para cada encarregado\nligado aos menores:\nenviar resumo e link;
  end fork
  |Treinador|
  :Vê confirmação na interface;
else (não)
  |Sistema|
  :Responder com erro de\nvalidação negocial;
endif
stop

@enduml
