@startuml atividade_registo
!include _cap_skin.puml
title Diagrama de atividade — **Registo de utilizador**

|Utilizador|
start
:Solicita registo e envia\ndados obrigatórios;

|Sistema (API + domínio)|
:Validar formato /\nregras básicas;

if (Email já existe?) then (sim)
  |Sistema|
  :Responder **409** /\nmensagem guiada;
  stop
else (não)
  |Sistema|
  :Derivar hash segura\nda palavra‑passe;
  :Persistir conta com\nestado **Pendente**;
  :Emitir evento de\nnotificação;
  |Secretaria|
  :Recebe alerta na área\nadministrativa;
  |Utilizador|
  :Vê ecrã de confirmação\nde submissão;
  stop
endif

@enduml
