@startuml casos_uso_desportiva
skinparam monochrome true
skinparam shadowing false
left to right direction

actor "Treinador" as Coach
actor "Encarregado\nEducação" as Parent
actor "Atleta" as Athlete

rectangle "Subsistema: Gestão Desportiva" {
    usecase "Gerir Plantéis" as UC_ManageSquad
    usecase "Criar Convocatória" as UC_CreateCallout
    usecase "Validar Convocatória" as UC_ValidateCallout
    usecase "Publicar Convocatória" as UC_PublishCallout
    usecase "Responder\nConvocatória" as UC_RespondCallout
    usecase "Consultar Calendário" as UC_ViewCalendar
    usecase "Registar Estatísticas\nJogo" as UC_LogGameStats
}

Coach --> UC_ManageSquad
Coach --> UC_CreateCallout
Coach --> UC_ValidateCallout
Coach --> UC_PublishCallout
Coach --> UC_LogGameStats
Coach --> UC_ViewCalendar

Athlete --> UC_RespondCallout
Parent --> UC_RespondCallout
Athlete --> UC_ViewCalendar
Parent --> UC_ViewCalendar

UC_CreateCallout .> UC_ValidateCallout : validar dados
UC_ValidateCallout .> UC_PublishCallout : após ok
UC_PublishCallout .> UC_RespondCallout : enviadas notificações

@enduml
