// <auto-generated />
using System;
using CAP.Modules.Sports.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CAP.Modules.Sports.Data.Migrations
{
    [DbContext(typeof(SportsDbContext))]
    [Migration("20260525155813_UpdateSistemaGeral")]
    partial class UpdateSistemaGeral
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sports")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.AtletaEquipa", b =>
                {
                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AtletaId", "EquipaId");

                    b.HasIndex("EquipaId");

                    b.ToTable("AtletaEquipas", "sports");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.AvaliacaoQualitativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Empenho")
                        .HasColumnType("integer");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tatica")
                        .HasColumnType("integer");

                    b.Property<int>("Tecnica")
                        .HasColumnType("integer");

                    b.Property<Guid>("TreinadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TreinoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AvaliacoesQualitativas", "sports");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Convite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConvocatoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("Presenca")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConvocatoriaId");

                    b.ToTable("Convites", "sports");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Convocatoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipaId");

                    b.ToTable("Convocatorias", "sports");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Equipa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EscalaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModalidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TreinadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EscalaoId");

                    b.HasIndex("ModalidadeId");

                    b.ToTable("Equipas", "sports");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Escalao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("IdadeMaxima")
                        .HasColumnType("integer");

                    b.Property<int>("IdadeMinima")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Escaloes", "sports");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Modalidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Modalidades", "sports");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.OcorrenciaJogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Minuto")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OcorrenciasJogo", "sports");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.PresencaTreino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("Justificacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TreinoId");

                    b.ToTable("PresencasTreino", "sports");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Treino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EquipaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EspacoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EquipaId");

                    b.ToTable("Treinos", "sports");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.AtletaEquipa", b =>
                {
                    b.HasOne("CAP.Modules.Sports.Core.Domain.Equipa", "Equipa")
                        .WithMany("Atletas")
                        .HasForeignKey("EquipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipa");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Convite", b =>
                {
                    b.HasOne("CAP.Modules.Sports.Core.Domain.Convocatoria", null)
                        .WithMany("Convites")
                        .HasForeignKey("ConvocatoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Convocatoria", b =>
                {
                    b.HasOne("CAP.Modules.Sports.Core.Domain.Equipa", "Equipa")
                        .WithMany()
                        .HasForeignKey("EquipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipa");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Equipa", b =>
                {
                    b.HasOne("CAP.Modules.Sports.Core.Domain.Escalao", "Escalao")
                        .WithMany()
                        .HasForeignKey("EscalaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CAP.Modules.Sports.Core.Domain.Modalidade", "Modalidade")
                        .WithMany("Equipas")
                        .HasForeignKey("ModalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escalao");

                    b.Navigation("Modalidade");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.PresencaTreino", b =>
                {
                    b.HasOne("CAP.Modules.Sports.Core.Domain.Treino", null)
                        .WithMany("Presencas")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Treino", b =>
                {
                    b.HasOne("CAP.Modules.Sports.Core.Domain.Equipa", "Equipa")
                        .WithMany()
                        .HasForeignKey("EquipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipa");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Convocatoria", b =>
                {
                    b.Navigation("Convites");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Equipa", b =>
                {
                    b.Navigation("Atletas");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Modalidade", b =>
                {
                    b.Navigation("Equipas");
                });

            modelBuilder.Entity("CAP.Modules.Sports.Core.Domain.Treino", b =>
                {
                    b.Navigation("Presencas");
                });
#pragma warning restore 612, 618
        }
    }
}
