@startuml

left to right direction

actor "Utilizador\nAutenticado" as User
actor "Atleta" as Athlete
actor "Encarregado" as Parent
actor "Treinador" as Coach

Athlete --|> User
Parent --|> User
Coach --|> User

rectangle "Subsistema: Gestão Desportiva e Treinos" {
    usecase "Consultar Plantel" as UC_ManageSquad
    usecase "Marcar Treino" as UC_ScheduleTraining
    usecase "Registar Assiduidade" as UC_TrackAttendance
    usecase "Criar Convocatória" as UC_CreateCallout
    usecase "Publicar Convocatória" as UC_PublishCallout
    usecase "Responder Convocatória" as UC_RespondCallout
    usecase "Registar Estatísticas de Jogo" as UC_LogGameStats
}

Coach --> UC_ManageSquad
Coach --> UC_ScheduleTraining
Coach --> UC_TrackAttendance
Coach --> UC_CreateCallout
Coach --> UC_PublishCallout
Coach --> UC_LogGameStats

Athlete --> UC_RespondCallout
Parent --> UC_RespondCallout

Athlete --> UC_ManageSquad
Coach --> UC_RespondCallout : consulta respostas

@enduml
