server {
    listen 80;

    # Onde os ficheiros estáticos do React vão estar
    root /usr/share/nginx/html;
    index index.html;

    # Reverse Proxy para a API
    # Redireciona tudo o que vier para /api para o contentor "api" no porto 80
    location /api/ {
        proxy_pass http://api:80/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Redireciona tudo o que vier para /swagger para o contentor "api"
    location /swagger/ {
        proxy_pass http://api:80/swagger/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Fallback routing para Single Page Applications (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
