// <auto-generated />
using System;
using CAP.Modules.Facilities.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CAP.Modules.Facilities.Data.Migrations
{
    [DbContext(typeof(FacilitiesDbContext))]
    [Migration("20260525083754_InitialFacilities")]
    partial class InitialFacilities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("facilities")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CAP.Modules.Facilities.Core.Domain.Espaco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Espacos", "facilities");
                });

            modelBuilder.Entity("CAP.Modules.Facilities.Core.Domain.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EspacoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsManutencao")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RequisitanteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EspacoId");

                    b.ToTable("Reservas", "facilities");
                });

            modelBuilder.Entity("CAP.Modules.Facilities.Core.Domain.Reserva", b =>
                {
                    b.HasOne("CAP.Modules.Facilities.Core.Domain.Espaco", "Espaco")
                        .WithMany()
                        .HasForeignKey("EspacoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espaco");
                });
#pragma warning restore 612, 618
        }
    }
}
