// <auto-generated />
using System;
using CAP.Modules.Finance.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CAP.Modules.Finance.Data.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CAP.Modules.Finance.Core.Domain.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Metodo")
                        .HasColumnType("integer");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Pagamentos", "finance");
                });

            modelBuilder.Entity("CAP.Modules.Finance.Core.Domain.Quota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuotaDefinicaoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("QuotaDefinicaoId");

                    b.ToTable("Quotas", "finance");
                });

            modelBuilder.Entity("CAP.Modules.Finance.Core.Domain.QuotaDefinicao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("QuotaDefinicoes", "finance");
                });

            modelBuilder.Entity("CAP.Modules.Finance.Core.Domain.Recibo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroRecibo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PagamentoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("NumeroRecibo")
                        .IsUnique();

                    b.HasIndex("PagamentoId");

                    b.ToTable("Recibos", "finance");
                });

            modelBuilder.Entity("PagamentoQuota", b =>
                {
                    b.Property<Guid>("PagamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuotasLiquidadasId")
                        .HasColumnType("uuid");

                    b.HasKey("PagamentoId", "QuotasLiquidadasId");

                    b.HasIndex("QuotasLiquidadasId");

                    b.ToTable("PagamentoQuota", "finance");
                });

            modelBuilder.Entity("CAP.Modules.Finance.Core.Domain.Quota", b =>
                {
                    b.HasOne("CAP.Modules.Finance.Core.Domain.QuotaDefinicao", "Definicao")
                        .WithMany()
                        .HasForeignKey("QuotaDefinicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definicao");
                });

            modelBuilder.Entity("CAP.Modules.Finance.Core.Domain.Recibo", b =>
                {
                    b.HasOne("CAP.Modules.Finance.Core.Domain.Pagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("PagamentoQuota", b =>
                {
                    b.HasOne("CAP.Modules.Finance.Core.Domain.Pagamento", null)
                        .WithMany()
                        .HasForeignKey("PagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CAP.Modules.Finance.Core.Domain.Quota", null)
                        .WithMany()
                        .HasForeignKey("QuotasLiquidadasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
