// <auto-generated />
using System;
using CAP.Modules.Reports.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CAP.Modules.Reports.Data.Migrations
{
    [DbContext(typeof(ReportsDbContext))]
    [Migration("20260525083800_InitialReports")]
    partial class InitialReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reports")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CAP.Modules.Reports.Core.Domain.ResumoDesportivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipaId")
                        .HasColumnType("uuid");

                    b.Property<string>("EquipaNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MediaPresencas")
                        .HasColumnType("double precision");

                    b.Property<int>("NumeroAtletas")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroConvocatorias")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ResumosDesportivos", "reports");
                });

            modelBuilder.Entity("CAP.Modules.Reports.Core.Domain.ResumoFinanceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroPagamentos")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPendente")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalRecebido")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ResumosFinanceiros", "reports");
                });
#pragma warning restore 612, 618
        }
    }
}
